# Generated by Django 4.0.8 on 2023-03-16 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name_plural': 'User statuses'},
        ),
    ]
